# 1. MySQLへの接続設定（データベース名を「attendance_db」とする場合）
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_db?upperCaseIdentifiers=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=【★各自のMySQLパスワード】
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8085

# 2. JPA/Hibernateの設定（起動時にテーブルがなければ自動生成する設定）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect